LunarLanderContinuous-v2:
  n_timesteps: !!float 2e6
  n_envs: 12
  policy: 'BSACMlpPolicy'
  batch_size: 256
  sac_lr: lin_7.3e-4
  bisim_lr: 1.0e-3
  buffer_size: 1000000
  ent_coef: 'auto'
  gamma: 0.99
  tau: 0.01
  train_freq: 1
  gradient_steps: 1
  learning_starts: 10000
  bisim_kwargs: "dict(C=0.5, K=1.0, grad_penalty=1e-3)"
  bisim_critic_kwargs: "dict(orth_init=True)"
  policy_kwargs: "dict(share_features_extractor=True, features_extractor_class='CustomMLP', features_extractor_kwargs=dict(orth_init=True, net_arch=[16]), net_arch=[400, 300])"

HalfCheetah-v4:
  n_timesteps: !!float 1e6
  policy: 'BSACMlpPolicy'
  n_envs: 10
  learning_starts: 10000
  bisim_lr: 1.0e-4
  bisim_kwargs: "dict(C=1.0, K=1.0, grad_penalty=10.0, critic_training_steps=1)"
  policy_kwargs: "dict(share_features_extractor=True, features_extractor_class='CustomMLP', net_arch=[400, 300])"