LunarLanderContinuous-v2:
  n_timesteps: !!float 2e6
  n_envs: 12
  policy: 'BSACMlpPolicy'
  batch_size: 256
  sac_lr: lin_7.3e-4
  bisim_lr: 1.0e-4
  buffer_size: 1000000
  ent_coef: 'auto'
  gamma: 0.99
  tau: 0.01
  train_freq: 1
  gradient_steps: 1
  learning_starts: 10000
  bisim_c: 0.5
  bisim_k: 1.0
  bisim_grad_penalty: 1.0
  features_extractor_class: 'CustomMLP'
  features_extractor_kwargs: 'dict(orth_init=True, net_arch=[16])'
  policy_kwargs: "dict(net_arch=[400, 300])"
  bisim_critic_kwargs: "dict(orth_init=True)"