LunarLanderContinuous-v2:
  n_timesteps: !!float 5e5
  n_envs: 12
  policy: 'BSACMlpPolicy'
  batch_size: 256
  sac_lr: 3.2e-4
  bisim_lr: 8.5e-4
  buffer_size: 1000000
  ent_coef: 'auto'
  gamma: 0.99
  tau: 0.01
  train_freq: 1
  gradient_steps: 1
  learning_starts: 10000
  bisim_c: 0.3
  bisim_k: 1.0
  bisim_use_q: False
  bisim_grad_penalty: 10.0
  features_extractor_class: 'CustomMLP'
  features_extractor_kwargs: 'dict(orth_init=True, net_arch=[16])'
  policy_kwargs: "dict(net_arch=[400, 300])"
  bisim_critic_kwargs: "dict(orth_init=True)"
