LunarLanderContinuous-v2:
  n_timesteps: !!float 5e5
  n_envs: 8
  policy: 'BSACMlpPolicy'
  batch_size: 256
  sac_lr: lin_2.5e-4
  bisim_lr: 1.0e-4
  buffer_size: 1000000
  ent_coef: 'auto'
  gamma: 0.99
  tau: 0.01
  train_freq: 1
  gradient_steps: 1
  learning_starts: 10000
  bisim_kwargs: "dict(C=1.0, K=1.0, grad_penalty=10.0, critic_training_steps=1)"
  policy_kwargs: "dict(share_features_extractor=True, features_extractor_class='CustomMLP', net_arch=[400, 300])"
