from bc4rl.encoder import CustomMLP, CustomCombinedExtractor

hyperparams = {
    "LunarLanderContinuous-v2": {
        "n_timesteps": 5e5,
        "n_envs": 12,
        "policy": "BSACMlpPolicy",
        "batch_size": 256,
        "sac_lr": "lin_7.3e-4",
        "bisim_lr": 1.0e-3,
        "buffer_size": 1000000,
        "ent_coef": "auto",
        "gamma": 0.99,
        "tau": 0.01,
        "train_freq": 1,
        "gradient_steps": 1,
        "learning_starts": 10000,
        "bisim_c": 0.5,
        "bisim_k": 1.0,
        "bisim_use_q": True,
        "bisim_grad_penalty": 1.0,
        "features_extractor_class": CustomMLP,
        "features_extractor_kwargs": {"ortho_init": True, "net_arch": [16]},
        "policy_kwargs": {"net_arch": [400, 300]},
        "bisim_critic_kwargs": {"ortho_init": True},
    },
    "BipedalWalker-v3": {
        "n_timesteps": 5e5,
        "n_envs": 12,
        "policy": "BSACMlpPolicy",
        "sac_lr": 7.3e-4,
        "bisim_lr": 5.0e-4,
        "buffer_size": 300000,
        "batch_size": 256,
        "ent_coef": "auto",
        "gamma": 0.98,
        "tau": 0.02,
        "train_freq": 64,
        "gradient_steps": 64,
        "learning_starts": 10000,
        "use_sde": True,
        "bisim_c": 0.5,
        "bisim_k": 1.0,
        "bisim_use_q": True,
        "bisim_grad_penalty": 1.0,
        "features_extractor_class": CustomMLP,
        "features_extractor_kwargs": {"ortho_init": True, "features_dim": 32, "net_arch": [32]},
        "bisim_critic_kwargs": {"ortho_init": True},
        "policy_kwargs": {"log_std_init": -3, "net_arch": [400, 300]},
    },
    "dm_control/cheetah-run-v0": {
        "n_timesteps": 2e6,
        "n_envs": 12,
        "policy": "BSACMultiInputPolicy",
        "batch_size": 256,
        "sac_lr": "lin_7.3e-4",
        "bisim_lr": 5.0e-4,
        "buffer_size": 10000,
        "ent_coef": "auto",
        "gamma": 0.99,
        "tau": 0.01,
        "train_freq": 1,
        "gradient_steps": 1,
        "learning_starts": 10000,
        "bisim_c": 0.5,
        "bisim_k": 1.0,
        "bisim_use_q": True,
        "bisim_grad_penalty": 1.0,
        "features_extractor_class": CustomCombinedExtractor,
        "env_wrapper": "gymnasium.wrappers.PixelObservationWrapper",
        "frame_stack": 3,
        "bisim_critic_kwargs": {"ortho_init": True},
    },
}
